// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/arvinpaundra/ngekost-api/internal/entity"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	request "github.com/arvinpaundra/ngekost-api/internal/adapter/request"
)

// KostRuleRepository is an autogenerated mock type for the KostRuleRepository type
type KostRuleRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, ruleId
func (_m *KostRuleRepository) Delete(ctx context.Context, ruleId string) error {
	ret := _m.Called(ctx, ruleId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, ruleId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteWithTx provides a mock function with given fields: ctx, tx, ruleId
func (_m *KostRuleRepository) DeleteWithTx(ctx context.Context, tx *gorm.DB, ruleId string) error {
	ret := _m.Called(ctx, tx, ruleId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) error); ok {
		r0 = rf(ctx, tx, ruleId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindById provides a mock function with given fields: ctx, ruleId
func (_m *KostRuleRepository) FindById(ctx context.Context, ruleId string) (*entity.KostRule, error) {
	ret := _m.Called(ctx, ruleId)

	var r0 *entity.KostRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.KostRule, error)); ok {
		return rf(ctx, ruleId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.KostRule); ok {
		r0 = rf(ctx, ruleId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.KostRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ruleId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByKostId provides a mock function with given fields: ctx, kostId, query
func (_m *KostRuleRepository) FindByKostId(ctx context.Context, kostId string, query *request.Common) ([]*entity.KostRule, error) {
	ret := _m.Called(ctx, kostId, query)

	var r0 []*entity.KostRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *request.Common) ([]*entity.KostRule, error)); ok {
		return rf(ctx, kostId, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *request.Common) []*entity.KostRule); ok {
		r0 = rf(ctx, kostId, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.KostRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *request.Common) error); ok {
		r1 = rf(ctx, kostId, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, rule
func (_m *KostRuleRepository) Save(ctx context.Context, rule *entity.KostRule) error {
	ret := _m.Called(ctx, rule)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.KostRule) error); ok {
		r0 = rf(ctx, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveWithTx provides a mock function with given fields: ctx, tx, rule
func (_m *KostRuleRepository) SaveWithTx(ctx context.Context, tx *gorm.DB, rule *entity.KostRule) error {
	ret := _m.Called(ctx, tx, rule)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.KostRule) error); ok {
		r0 = rf(ctx, tx, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, rule, ruleId
func (_m *KostRuleRepository) Update(ctx context.Context, rule *entity.KostRule, ruleId string) error {
	ret := _m.Called(ctx, rule, ruleId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.KostRule, string) error); ok {
		r0 = rf(ctx, rule, ruleId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateWithTx provides a mock function with given fields: ctx, tx, rule, ruleId
func (_m *KostRuleRepository) UpdateWithTx(ctx context.Context, tx *gorm.DB, rule *entity.KostRule, ruleId string) error {
	ret := _m.Called(ctx, tx, rule, ruleId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.KostRule, string) error); ok {
		r0 = rf(ctx, tx, rule, ruleId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKostRuleRepository creates a new instance of KostRuleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKostRuleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *KostRuleRepository {
	mock := &KostRuleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
