// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"

	contract "github.com/arvinpaundra/ngekost-api/internal/driver/contract"
	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// Transactioner is an autogenerated mock type for the Transactioner type
type Transactioner struct {
	mock.Mock
}

// Begin provides a mock function with given fields: ctx, opts
func (_m *Transactioner) Begin(ctx context.Context, opts ...*sql.TxOptions) (contract.Transaction, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 contract.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...*sql.TxOptions) (contract.Transaction, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...*sql.TxOptions) contract.Transaction); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contract.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...*sql.TxOptions) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactioner creates a new instance of Transactioner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactioner(t interface {
	mock.TestingT
	Cleanup(func())
}) *Transactioner {
	mock := &Transactioner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
